// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package ling

import "strconv"

const _TokenType_name = "EOFSpaceSymbolNumberLettersPunctWord"

var _TokenType_index = [...]uint8{0, 3, 8, 14, 20, 27, 32, 36}

func (i TokenType) String() string {
	if i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
